name: Auto-Track UH AI Project

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # For pushing back

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch  # Add any deps your script needs (e.g., if using torch for future)

      - name: Run tracker script
        run: python uh_ai_project_tracker.py --no-clone --output-file tracker_log.md

      - name: Commit and push changes if any
        uses: EndBug/add-and-commit@v9
        with:
          add: 'tracker_log.md'
          message: 'Auto-update tracker log with latest repo report'
          default_author: github_actions
          pull_strategy: 'NO-PULL'  # Avoid conflicts